version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq

  frontend:
    build: ./front-end
    ports:
      - "5173:5173"
    command: npm run dev

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
