version: '3.8'

services:
  api:
    build:
      context: ./api/DesafioVsoft
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # --- Configurações do RabbitMQ para a API ---
      - RabbitMQ:HostName=rabbitmq # <--- AQUI ESTÁ A CHAVE! Use o nome do serviço do RabbitMQ
      - RabbitMQ:UserName=guest    # <--- Usuário padrão do RabbitMQ
      - RabbitMQ:Password=guest    # <--- Senha padrão do RabbitMQ
      - RabbitMQ:VirtualHost=/     # <--- Virtual Host padrão do RabbitMQ (geralmente '/')

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Nginx serve na porta 80
