version: '3.8'

services:
  api:
    build:
      context: ./api/DesafioVsoft
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./front-end:/app
    ports:
      - "5100:5173"
    command: sh -c "npm install && npm run dev"
